name: brew test-bot
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-bot:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Checkout tap
        uses: actions/checkout@v4
        with:
          path: homebrew-git-flow-pro

      - name: Setup tap
        run: |
          mkdir -p "$(brew --repo)/Library/Taps/chornthorn"
          cp -r homebrew-git-flow-pro "$(brew --repo)/Library/Taps/chornthorn/"
          brew tap

      - name: Install shellcheck
        run: brew install shellcheck

      - name: Run tests
        run: |
          cd "$(brew --repo)/Library/Taps/chornthorn/homebrew-git-flow-pro"
          brew style chornthorn/git-flow-pro
          brew test-bot --only-tap-syntax
          brew audit --strict chornthorn/git-flow-pro/git-flow-pro
          brew install --build-from-source chornthorn/git-flow-pro/git-flow-pro
          brew test chornthorn/git-flow-pro/git-flow-pro

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: brew-logs
          path: ~/Library/Logs/Homebrew/
