name: Update Formula
on:
  repository_dispatch:
    types: [update-formula]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Update Formula
        env:
          VERSION: ${{ github.event.client_payload.version }}
          SHA256: ${{ github.event.client_payload.sha256 }}
        run: |
          # Remove 'v' prefix if present
          VERSION_NO_V=$(echo ${VERSION} | sed 's/^v//')

          # Update formula
          sed -i "s/version \".*\"/version \"${VERSION_NO_V}\"/" Formula/git-flow-pro.rb
          sed -i "s/sha256 \".*\"/sha256 \"${SHA256}\"/" Formula/git-flow-pro.rb
          sed -i "s|/v.*\.tar\.gz|/${VERSION}.tar.gz|" Formula/git-flow-pro.rb

      - name: Commit and Push
        run: |
          git add Formula/git-flow-pro.rb
          git commit -m "Update formula to version ${VERSION}"
          git push

      - name: Verify Formula
        run: |
          brew tap chornthorn/git-flow-pro
          brew audit --strict --online git-flow-pro
