name: Update Formula
on:
  repository_dispatch:
    types: [update-formula]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Checkout tap
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          fetch-depth: 0
          path: homebrew-git-flow-pro

      - name: Setup tap
        run: |
          TAP_PATH="$(brew --repo)/Library/Taps/chornthorn"
          rm -rf "$TAP_PATH/homebrew-git-flow-pro"
          mkdir -p "$TAP_PATH"
          cp -r homebrew-git-flow-pro "$TAP_PATH/"
          cd "$TAP_PATH/homebrew-git-flow-pro" || exit 1
          brew tap --force chornthorn/git-flow-pro
          brew update

      - name: Update Formula
        env:
          VERSION: ${{ github.event.client_payload.version }}
          SHA256: ${{ github.event.client_payload.sha256 }}
        run: |
          cd "$(brew --repo)/Library/Taps/chornthorn/homebrew-git-flow-pro" || exit 1
          if [ -z "${VERSION}" ] || [ -z "${SHA256}" ]; then
            echo "Error: Version or SHA256 not provided"
            exit 1
          fi
          sed -i.bak "s|url \"https://github.com/chornthorn/git-flow-pro/archive/refs/tags/.*\.tar\.gz\"|url \"https://github.com/chornthorn/git-flow-pro/archive/refs/tags/${VERSION}.tar.gz\"|" Formula/git-flow-pro.rb
          sed -i.bak "s|sha256 \"[a-fA-F0-9]*\"|sha256 \"${SHA256}\"|" Formula/git-flow-pro.rb

      - name: Verify Formula
        run: |
          cd "$(brew --repo)/Library/Taps/chornthorn/homebrew-git-flow-pro" || exit 1
          brew audit --strict --online git-flow-pro
          brew style git-flow-pro

      - name: Configure Git
        run: |
          cd "$(brew --repo)/Library/Taps/chornthorn/homebrew-git-flow-pro"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit Changes
        run: |
          cd "$(brew --repo)/Library/Taps/chornthorn/homebrew-git-flow-pro" || exit 1
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git add Formula/git-flow-pro.rb
          git commit -m "Update formula to version ${VERSION}"
          git push origin HEAD:main || exit 1

      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          commit-message: "Update formula to version ${{ github.event.client_payload.version }}"
          title: "Update formula to version ${{ github.event.client_payload.version }}"
          body: |
            Automated update of Git Flow Pro formula to version ${{ github.event.client_payload.version }}

            SHA256: `${{ github.event.client_payload.sha256 }}`

            This PR was automatically created by GitHub Actions.
          branch: update-formula
          base: main
          delete-branch: true

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: brew-logs
          path: |
            ~/Library/Logs/Homebrew/
            $(brew --repo)/Library/Logs/Homebrew/

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Formula update failed for version ${process.env.VERSION}`,
              body: 'The formula update workflow failed. Please check the logs.',
              labels: ['bug', 'automation']
            });
