name: Update Formula
on:
  repository_dispatch:
    types: [update-formula]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Checkout tap
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-git-flow-pro

      - name: Setup tap
        run: |
          mkdir -p "$(brew --repo)/Library/Taps/chornthorn"
          cp -r homebrew-git-flow-pro "$(brew --repo)/Library/Taps/chornthorn/"
          brew tap

      - name: Configure Git
        run: |
          cd "$(brew --repo)/Library/Taps/chornthorn/homebrew-git-flow-pro"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Formula
        env:
          VERSION: ${{ github.event.client_payload.version }}
          SHA256: ${{ github.event.client_payload.sha256 }}
        run: |
          cd "$(brew --repo)/Library/Taps/chornthorn/homebrew-git-flow-pro"
          if [ -z "$VERSION" ] || [ -z "$SHA256" ]; then
            echo "Error: Version or SHA256 not provided"
            exit 1
          fi
          sed -i 's|url ".*"|url "https://github.com/chornthorn/git-flow-pro/archive/refs/tags/'"${VERSION}"'.tar.gz"|' Formula/git-flow-pro.rb
          sed -i 's|sha256 ".*"|sha256 "'"${SHA256}"'"|' Formula/git-flow-pro.rb

      - name: Verify Formula
        run: brew audit --strict --online chornthorn/git-flow-pro

      - name: Test Formula
        run: |
          brew install --build-from-source chornthorn/git-flow-pro/git-flow-pro
          brew test chornthorn/git-flow-pro/git-flow-pro

      - name: Commit Changes
        run: |
          cd "$(brew --repo)/Library/Taps/chornthorn/homebrew-git-flow-pro"
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git add Formula/git-flow-pro.rb
          git commit -m "Update formula to version ${VERSION}"
          git push

      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          commit-message: "Update formula to version ${{ github.event.client_payload.version }}"
          title: "Update formula to version ${{ github.event.client_payload.version }}"
          body: |
            Automated update of Git Flow Pro formula to version ${{ github.event.client_payload.version }}

            SHA256: `${{ github.event.client_payload.sha256 }}`

            This PR was automatically created by GitHub Actions.
          branch: update-formula
          base: main
          delete-branch: true

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: brew-logs
          path: |
            ~/Library/Logs/Homebrew/
            $(brew --repo)/Library/Logs/Homebrew/

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Formula update failed',
              body: 'The formula update workflow failed. Please check the logs.',
              labels: ['bug', 'automation']
            });
